# Generated by Django 3.2.3 on 2021-06-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=64)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=16, verbose_name='phone number')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('national_id', models.CharField(max_length=10, verbose_name='national id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
