# Generated by Django 3.2.3 on 2021-06-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_to_image',
            field=models.CharField(max_length=256),
        ),
    ]
